### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Felli** [GreenMeteor/humhub-outerlimits-theme#4]
The following is a list of things planned or wanted to be added to the theme.

- [ ] Background Changer (#3)
- [ ] Implement color changer similar to [Theme Builder](https://www.humhub.org/en/marketplace/details?id=36) module.
- [x] Fix email registration issues.
- [x] Implement Reset button on login page.

> Notice: This issue is subject to change at any time that a @GreenMeteor/core-members or @GreenMeteor/developers feels the need to add more or remove something from the Roadmap.
